- name: Cài K3s server trên master
  when: inventory_hostname in groups['masters']
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Lấy token của K3s server
  when: inventory_hostname in groups['masters']
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false

- name: Ghi token ra file tạm để agent đọc
  when: inventory_hostname in groups['masters']
  copy:
    content: "{{ k3s_token.stdout }}"
    dest: "/tmp/k3s_token.txt"
    mode: '0644'

- name: Lay token từ master
  when: inventory_hostname in groups['workers']
  delegate_to: "{{ groups['masters'][0] }}"
  fetch:
    src: /tmp/k3s_token.txt
    dest: /tmp/k3s_token.txt
    flat: yes

- name: Cài K3s agent
  when: inventory_hostname in groups['workers']
  shell: |
    export K3S_URL="https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443"
    export K3S_TOKEN="{{ lookup('file', '/tmp/k3s_token.txt') }}"
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s-agent
